KubusBackendBundle_role:
  resource: "@KubusBackendBundle/Resources/config/routing/role.yml"
  prefix:   /role

KubusBackendBundle_attributes:
  resource: "@KubusBackendBundle/Resources/config/routing/attributes.yml"
  prefix:   /attributes

KubusBackendBundle_tool:
  resource: "@KubusBackendBundle/Resources/config/routing/tool.yml"
  prefix:   /tool

KubusBackendBundle_application:
  resource: "@KubusBackendBundle/Resources/config/routing/application.yml"
  prefix:   /application

KubusBackendBundle_lessonteacher:
  resource: "@KubusBackendBundle/Resources/config/routing/lessonteacher.yml"
  prefix:   /lessonteacher

KubusBackendBundle_lessontool:
  resource: "@KubusBackendBundle/Resources/config/routing/lessontool.yml"
  prefix:   /lessontool

KubusBackendBundle_lessonlocation:
  resource: "@KubusBackendBundle/Resources/config/routing/lessonlocation.yml"
  prefix:   /lessonlocation

KubusBackendBundle_lessondate:
  resource: "@KubusBackendBundle/Resources/config/routing/lessondate.yml"
  prefix:   /lessondate

KubusBackendBundle_audience:
  resource: "@KubusBackendBundle/Resources/config/routing/audience.yml"
  prefix:   /audience

KubusBackendBundle_subcategory:
  resource: "@KubusBackendBundle/Resources/config/routing/subcategory.yml"
  prefix:   /subcategory

KubusBackendBundle_category:
  resource: "@KubusBackendBundle/Resources/config/routing/category.yml"
  prefix:   /category

KubusBackendBundle_program:
  resource: "@KubusBackendBundle/Resources/config/routing/program.yml"
  prefix:   /program

KubusBackendBundle_lesson:
  resource: "@KubusBackendBundle/Resources/config/routing/lesson.yml"
  prefix:   /lesson

kubus_backend_person:
  resource: "@KubusBackendBundle/Resources/config/routing/person.yml"
  prefix: /person

KubusBackendBundle_teacher:
  resource: "@KubusBackendBundle/Resources/config/routing/teacher.yml"
  prefix:   /teacher

KubusBackendBundle_course:
  resource: "@KubusBackendBundle/Resources/config/routing/course.yml"
  prefix: /course

login:
    pattern: /login
    defaults: { _controller: KubusBackendBundle:Authentication:login }

logout:
    pattern: /logout
    defaults: { _controller: KubusBackendBundle:Authentication:logout }

index:
    pattern: /
    defaults: { _controller: KubusBackendBundle:Navigation:index }